"""init

Revision ID: 39aa156b9acf
Revises: 
Create Date: 2024-05-26 10:31:34.501010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39aa156b9acf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('users')
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    op.create_table('users',
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_pin', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('username', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('log_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], name='logs_username_fkey'),
    sa.PrimaryKeyConstraint('id', name='logs_pkey')
    )
    # ### end Alembic commands ###
