import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { jsPDF } from 'jspdf';
import { Container, Typography, Box, Table, TableHead, TableRow, TableCell, TableBody, TableSortLabel, Button } from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import PrintIcon from '@mui/icons-material/Print';
import { toast } from 'react-toastify';

interface Log {
    id: number;
    username: string;
    log_time: string;
    document_differences: string | null;
    interface: string;
}

const LogsPage: React.FC<{ token: string }> = ({ token }) => {
    const [logs, setLogs] = useState<Log[]>([]);
    const [sortColumn, setSortColumn] = useState<string>('');
    const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('asc');

    useEffect(() => {
        axios
            .get('http://localhost:8000/logs', {
                headers: {
                    Authorization: `Bearer ${token}`,
                },
            })
            .then((response) => {
                setLogs(response.data);
            })
            .catch((error) => {
                console.error('Error fetching logs', error);
                toast.error('Error fetching logs.');
            });
    }, [token]);

    const handleSort = (column: string) => {
        const direction = sortColumn === column && sortDirection === 'asc' ? 'desc' : 'asc';
        setSortColumn(column);
        setSortDirection(direction);

        const sortedLogs = [...logs].sort((a, b) => {
            if (a[column] < b[column]) return direction === 'asc' ? -1 : 1;
            if (a[column] > b[column]) return direction === 'asc' ? 1 : -1;
            return 0;
        });
        setLogs(sortedLogs);
    };

    const formatDifferences = (differences: string | null, truncate: boolean = false) => {
        if (!differences) return '';
        const formattedDifferences = differences
            .split('",')
            .map((diff, index) => `${index + 1}. ${diff}`)
            .join('\n\n');
        if (truncate) {
            const lines = formattedDifferences.split('\n\n');
            if (lines.length > 2) {
                return `${lines.slice(0, 2).join('\n\n')}...`;
            }
        }
        return formattedDifferences;
    };

    const generatePDF = (log: Log) => {
        const doc = new jsPDF();
        doc.setFontSize(12);
        doc.text("Excel Comparison Report", 10, 10);
        doc.text(`Report Date: ${new Date(log.log_time).toLocaleString()}`, 10, 20);
        doc.text(`Generated by: ${log.username}`, 10, 30);
        doc.text("Differences:", 10, 40);

        const differences = formatDifferences(log.document_differences).split('\n\n');
        let y = 50;
        differences.forEach((diff: string) => {
            doc.text(diff, 10, y);
            y += 10;
            if (y > 280) {
                doc.addPage();
                y = 10;
            }
        });

        doc.save("comparison_report.pdf");
        toast.success('PDF generated successfully!');
    };

    return (
        <Container>
            <Box display="flex" justifyContent="space-between" alignItems="center" mt={4} mb={4}>
                <Typography variant="h4" color="primary">Logs</Typography>
                <Button variant="contained" color="primary" startIcon={<ArrowBackIcon />} href="/">
                    Back to Compare
                </Button>
            </Box>
            <Table>
                <TableHead>
                    <TableRow>
                        <TableCell style={{ color: 'rgb(217,34,41)' }}>
                            <TableSortLabel
                                active={sortColumn === 'username'}
                                direction={sortColumn === 'username' ? sortDirection : 'asc'}
                                onClick={() => handleSort('username')}
                            >
                                Username
                            </TableSortLabel>
                        </TableCell>
                        <TableCell style={{ color: 'rgb(217,34,41)' }}>
                            <TableSortLabel
                                active={sortColumn === 'log_time'}
                                direction={sortColumn === 'log_time' ? sortDirection : 'asc'}
                                onClick={() => handleSort('log_time')}
                            >
                                Log Time
                            </TableSortLabel>
                        </TableCell>
                        <TableCell style={{ color: 'rgb(217,34,41)' }}>
                            <TableSortLabel
                                active={sortColumn === 'document_differences'}
                                direction={sortColumn === 'document_differences' ? sortDirection : 'asc'}
                                onClick={() => handleSort('document_differences')}
                            >
                                Document Differences
                            </TableSortLabel>
                        </TableCell>
                        <TableCell style={{ color: 'rgb(217,34,41)' }}>Interface</TableCell>
                    </TableRow>
                </TableHead>
                <TableBody>
                    {logs.map((log) => (
                        <TableRow key={log.id}>
                            <TableCell>{log.username}</TableCell>
                            <TableCell>{new Date(log.log_time).toLocaleString()}</TableCell>
                            <TableCell>
                                <pre className="whitespace-pre-wrap">{formatDifferences(log.document_differences, true)}</pre>
                                {log.document_differences && log.document_differences.split('",').length > 2 && (
                                    <Button
                                        onClick={() => generatePDF(log)}
                                        color="primary"
                                        startIcon={<PrintIcon />}
                                    >
                                        Proceed to Print To View More
                                    </Button>
                                )}
                            </TableCell>
                            <TableCell>{log.interface}</TableCell>
                        </TableRow>
                    ))}
                </TableBody>
            </Table>
        </Container>
    );
};

export default LogsPage;
